services:
  - type: web
    name: hospital-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_supabase:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
